name: Check Code PullRequest

on:
  pull_request:
    branches:
      - dev
      - qa
      - main

  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for infracost to write on pull requests.

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.base_ref }}
    steps:
      - name: Pull source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{vars.AWS_ROLE}}
          aws-region: ${{vars.AWS_REGION}}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Configure git credentials to pull terraform modules
        run: git config --global url."https://${{ secrets.USERNAME_GITHUB }}:${{ secrets.ACCESS_TOKEN }}@github.com".insteadOf https://github.com

      - name: Install boto3
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: State Checker
        env:
          AWS_BACKEND_ID: ${{vars.AWS_BACKEND}}
        run: |
          chmod +x state-checker.py  
          python3 state-checker.py $AWS_BACKEND_ID

      - name: Update Backend S3 configurations
        env:
          PROJECT_NAME: ${{vars.PROJECT_NAME}}
          AWS_BACKEND_ID: ${{vars.AWS_BACKEND}}
        run: |
          sed -i "s/BUCKET_NAME/$AWS_BACKEND_ID/" provider.tf
          sed -i "s/PROJECT_NAME/$PROJECT_NAME/" provider.tf
          cat provider.tf

      - name: Set Up Terraform Enviroment
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Set Up TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1

      - name: Analysis with tflint
        run: tflint

      - name: Analysis with Checkov
        continue-on-error: true
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        shell: bash
        run: |
          terraform plan -var-file=env/${{ github.base_ref }}.auto.tfvars -no-color > plan_output.txt
          echo "plan<<EOF" >> $GITHUB_OUTPUT
          cat plan_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # - name: Comment Plan
      #   id: comment-plan
      #   uses: peter-evans/create-or-update-comment@v2
      #   with:
      #     token: ${{ secrets.ACCESS_TOKEN }}
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body: |
      #       # Terraform Plan:
      #       ```
      #       ${{ steps.plan.outputs.plan }}